# Old bundled JDK was incomplete (missing lib\jvm.cfg): C:\\projects\\TimeManager\\jdk17\\jdk-17.0.20.1+1
org.gradle.java.home=C:\\Users\\TauSv~\\.jdks\\ms-17.0.20.1
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
# Room 2.6.1 несовместим с KSP2, оставляем KSP1
ksp.useKSP2=false
