package ru.taurlom.tnote.presentation.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import ru.taurlom.tnote.domain.model.ThemeKind

/**
 * Готовые темы: маппинг примитивов (Color.kt) в роли Material 3 и в
 * компонентные роли приложения. Новая тема = ещё один [AppThemeSpec] ниже
 * + значение в [ThemeKind], UI-код не меняется.
 */
internal data class AppThemeSpec(
    val colorScheme: ColorScheme,
    val colors: AppColors,
    /** Тёмные иконки системного стейтбара (для светлых фонов). */
    val lightStatusBar: Boolean = false,
)

/** Текущая основная тема приложения. */
internal val DarkTheme = AppThemeSpec(
    colorScheme = darkColorScheme(
        primary = Navy,
        onPrimary = Paper,
        primaryContainer = Slate,
        onPrimaryContainer = Sand,
        secondary = Gold,
        onSecondary = Navy,
        secondaryContainer = Gold,
        onSecondaryContainer = Navy,
        tertiary = Sand,
        onTertiary = Navy,
        background = Ink,
        onBackground = Snow,
        surface = Slate,
        onSurface = Snow,
        onSurfaceVariant = Sand,
        surfaceContainer = Sand,
        // Highest из наших компонентов читает только выключенный трек
        // Switch (пикер перекрыт своими ролями через AppColors): без
        // заполнения M3 подставляет серо-лавандовый дефолт мимо палитры.
        surfaceContainerHighest = Slate,
        outline = Sand,
    ),
    colors = AppColors(
        appBarContainer = Ink,
        appBarContent = Gold,
        dialogContainer = Sand,
        dialogContent = Navy,
        dialogContentMuted = Navy.copy(alpha = 0.6f),
        fieldContent = Navy,
        fieldBorder = Navy,
        fieldBorderUnfocused = Navy.copy(alpha = 0.6f),
        fieldOnDarkContent = Sand,
        fieldOnDarkBorder = Sand.copy(alpha = 0.6f),
        requiredMarker = Red,
        pickerBackdrop = Ink,
        pickerDial = Slate,
        pickerDialContent = Snow,
        pickerSelector = Navy,
        pickerSelectorContent = Snow,
        pickerChipSelectedContainer = Navy,
        pickerChipSelectedContent = Snow,
        buttonContainer = Navy,
        buttonContent = Paper,
        buttonDisabledContainer = Navy.copy(alpha = 0.5f),
        buttonDisabledContent = Paper.copy(alpha = 0.5f),
        chipSelectedContainer = Navy,
        chipSelectedContent = Paper,
        chipContainer = Navy.copy(alpha = 0.08f),
        chipContent = Navy,
        fabContainer = Gold,
        fabContent = Navy,
        actionIcon = Gold,
        bottomNavContainer = Ink,
        bottomNavIndicator = Gold,
        bottomNavActiveIcon = Navy,
        bottomNavInactiveIcon = Sand,
        calendarCellContainer = Ink,
        calendarWeekendContainer = Slate,
        calendarTodayContainer = Navy,
        calendarDayNumber = Sand,
        calendarTodayNumber = Sand,
        calendarAdjacentDayNumber = Navy,
        calendarHeader = Sand,
        calendarWeekdayLabel = Red,
        calendarEventMarker = Gold,
        calendarNoteMarker = Red,
        calendarPastMarker = Fog,
        sectionTitle = Gold,
        brandLogo = Gold,
        brandTitle = Gold,
        launchBackground = Ink,
        appBarScrolledContainer = Ink,
    ),
)

/** Светлая: тёплый бумажный фон, тёмно-синий акцент, янтарь вместо золота. */
internal val LightTheme = AppThemeSpec(
    colorScheme = lightColorScheme(
        primary = Navy,
        onPrimary = Paper,
        primaryContainer = Sand,
        onPrimaryContainer = Navy,
        secondary = Amber,
        onSecondary = Paper,
        secondaryContainer = Sand,
        onSecondaryContainer = Navy,
        tertiary = Sand,
        onTertiary = Navy,
        background = Cloud,
        onBackground = Navy,
        surface = Paper,
        onSurface = Navy,
        onSurfaceVariant = Slate,
        surfaceContainer = Sand,
        surfaceContainerHighest = Paper,
        outline = Slate,
    ),
    colors = AppColors(
        appBarContainer = Sand,
        appBarContent = Navy,
        dialogContainer = Paper,
        dialogContent = Navy,
        dialogContentMuted = Navy.copy(alpha = 0.6f),
        fieldContent = Navy,
        fieldBorder = Navy,
        fieldBorderUnfocused = Navy.copy(alpha = 0.6f),
        fieldOnDarkContent = Navy,
        fieldOnDarkBorder = Navy.copy(alpha = 0.6f),
        requiredMarker = Red,
        pickerBackdrop = Cloud,
        pickerDial = Sand,
        pickerDialContent = Navy,
        pickerSelector = Navy,
        pickerSelectorContent = Paper,
        pickerChipSelectedContainer = Navy,
        pickerChipSelectedContent = Paper,
        buttonContainer = Navy,
        buttonContent = Paper,
        buttonDisabledContainer = Navy.copy(alpha = 0.5f),
        buttonDisabledContent = Paper.copy(alpha = 0.5f),
        chipSelectedContainer = Navy,
        chipSelectedContent = Paper,
        chipContainer = Navy.copy(alpha = 0.08f),
        chipContent = Navy,
        fabContainer = Gold,
        fabContent = Navy,
        actionIcon = Amber,
        bottomNavContainer = Cloud,
        bottomNavIndicator = Sand,
        bottomNavActiveIcon = Navy,
        bottomNavInactiveIcon = Slate,
        calendarCellContainer = Cloud,
        calendarWeekendContainer = Sand,
        calendarTodayContainer = Navy,
        calendarDayNumber = Navy,
        calendarTodayNumber = Paper,
        calendarAdjacentDayNumber = Navy.copy(alpha = 0.4f),
        calendarHeader = Navy,
        calendarWeekdayLabel = Red,
        calendarEventMarker = Amber,
        calendarNoteMarker = Red,
        calendarPastMarker = Fog,
        sectionTitle = Amber,
        brandLogo = Navy,
        brandTitle = Navy,
        launchBackground = Ink,
        appBarScrolledContainer = Cloud,
    ),
    lightStatusBar = true,
)

/** Океан: глубокий сине-зелёный, акценты — коралл и бирюза. */
internal val OceanTheme = AppThemeSpec(
    colorScheme = darkColorScheme(
        primary = Teal,
        onPrimary = Foam,
        primaryContainer = Reef,
        onPrimaryContainer = Aqua,
        secondary = Coral,
        onSecondary = Abyss,
        secondaryContainer = Reef,
        onSecondaryContainer = Coral,
        tertiary = Aqua,
        onTertiary = Abyss,
        background = Abyss,
        onBackground = Foam,
        surface = Reef,
        onSurface = Foam,
        onSurfaceVariant = Aqua,
        surfaceContainer = Reef,
        surfaceContainerHighest = Reef,
        outline = Aqua,
    ),
    colors = AppColors(
        appBarContainer = Teal,
        appBarContent = Foam,
        dialogContainer = Reef,
        dialogContent = Foam,
        dialogContentMuted = Foam.copy(alpha = 0.6f),
        fieldContent = Foam,
        fieldBorder = Aqua,
        fieldBorderUnfocused = Aqua.copy(alpha = 0.6f),
        fieldOnDarkContent = Aqua,
        fieldOnDarkBorder = Aqua.copy(alpha = 0.6f),
        requiredMarker = Coral,
        pickerBackdrop = Abyss,
        pickerDial = Reef,
        pickerDialContent = Aqua,
        pickerSelector = Coral,
        pickerSelectorContent = Abyss,
        pickerChipSelectedContainer = Teal,
        pickerChipSelectedContent = Foam,
        buttonContainer = Teal,
        buttonContent = Foam,
        buttonDisabledContainer = Teal.copy(alpha = 0.5f),
        buttonDisabledContent = Foam.copy(alpha = 0.5f),
        chipSelectedContainer = Teal,
        chipSelectedContent = Foam,
        chipContainer = Aqua.copy(alpha = 0.12f),
        chipContent = Aqua,
        fabContainer = Coral,
        fabContent = Abyss,
        actionIcon = Coral,
        bottomNavContainer = Abyss,
        bottomNavIndicator = Teal,
        bottomNavActiveIcon = Foam,
        bottomNavInactiveIcon = Aqua,
        calendarCellContainer = Abyss,
        calendarWeekendContainer = Reef,
        calendarTodayContainer = Teal,
        calendarDayNumber = Foam,
        calendarTodayNumber = Foam,
        calendarAdjacentDayNumber = Fog,
        calendarHeader = Aqua,
        calendarWeekdayLabel = Coral,
        calendarEventMarker = Aqua,
        calendarNoteMarker = Coral,
        calendarPastMarker = Fog,
        sectionTitle = Coral,
        brandLogo = Foam,
        brandTitle = Foam,
        launchBackground = Ink,
        appBarScrolledContainer = Reef,
    ),
)

/** Лес: тёмная зелёно-коричневая, хвойный акцент и охра. */
internal val ForestTheme = AppThemeSpec(
    colorScheme = darkColorScheme(
        primary = Pine,
        onPrimary = Cream,
        primaryContainer = Bark,
        onPrimaryContainer = Moss,
        secondary = Clay,
        onSecondary = Cream,
        secondaryContainer = Bark,
        onSecondaryContainer = Clay,
        tertiary = Lichen,
        onTertiary = PineDark,
        background = Loam,
        onBackground = Cream,
        surface = Bark,
        onSurface = Cream,
        onSurfaceVariant = Moss,
        surfaceContainer = Lichen,
        surfaceContainerHighest = Bark,
        outline = Moss,
    ),
    colors = AppColors(
        appBarContainer = Walnut,
        appBarContent = Moss,
        dialogContainer = Lichen,
        dialogContent = PineDark,
        dialogContentMuted = PineDark.copy(alpha = 0.6f),
        fieldContent = PineDark,
        fieldBorder = PineDark,
        fieldBorderUnfocused = PineDark.copy(alpha = 0.6f),
        fieldOnDarkContent = Moss,
        fieldOnDarkBorder = Moss.copy(alpha = 0.6f),
        requiredMarker = Clay,
        pickerBackdrop = Loam,
        pickerDial = Bark,
        pickerDialContent = Moss,
        pickerSelector = Clay,
        pickerSelectorContent = Cream,
        pickerChipSelectedContainer = Pine,
        pickerChipSelectedContent = Cream,
        buttonContainer = Pine,
        buttonContent = Cream,
        buttonDisabledContainer = Pine.copy(alpha = 0.5f),
        buttonDisabledContent = Cream.copy(alpha = 0.5f),
        chipSelectedContainer = Pine,
        chipSelectedContent = Cream,
        chipContainer = PineDark.copy(alpha = 0.08f),
        chipContent = PineDark,
        fabContainer = Clay,
        fabContent = Cream,
        actionIcon = Clay,
        bottomNavContainer = Loam,
        bottomNavIndicator = Clay,
        bottomNavActiveIcon = Cream,
        bottomNavInactiveIcon = Moss,
        calendarCellContainer = Loam,
        calendarWeekendContainer = Bark,
        calendarTodayContainer = Pine,
        calendarDayNumber = Cream,
        calendarTodayNumber = Cream,
        calendarAdjacentDayNumber = Cream.copy(alpha = 0.4f),
        calendarHeader = Moss,
        calendarWeekdayLabel = Clay,
        calendarEventMarker = Clay,
        calendarNoteMarker = Red,
        calendarPastMarker = Fog,
        sectionTitle = Clay,
        brandLogo = Clay,
        brandTitle = Clay,
        launchBackground = Ink,
        appBarScrolledContainer = Bark,
    ),
)

/** Осень: тёплая кофейно-рыжая, охра и «выжженный» оранжевый. */
internal val AutumnTheme = AppThemeSpec(
    colorScheme = darkColorScheme(
        primary = Rust,
        onPrimary = Cream,
        primaryContainer = Umber,
        onPrimaryContainer = Wheat,
        secondary = Ochre,
        onSecondary = Espresso,
        secondaryContainer = Ochre,
        onSecondaryContainer = Espresso,
        tertiary = Wheat,
        onTertiary = Espresso,
        background = Espresso,
        onBackground = Cream,
        surface = Umber,
        onSurface = Cream,
        onSurfaceVariant = Wheat,
        surfaceContainer = Umber,
        surfaceContainerHighest = Umber,
        outline = Wheat,
    ),
    colors = AppColors(
        appBarContainer = Rust,
        appBarContent = Cream,
        dialogContainer = Parchment,
        dialogContent = Cocoa,
        dialogContentMuted = Cocoa.copy(alpha = 0.6f),
        fieldContent = Cocoa,
        fieldBorder = Cocoa,
        fieldBorderUnfocused = Cocoa.copy(alpha = 0.6f),
        fieldOnDarkContent = Wheat,
        fieldOnDarkBorder = Wheat.copy(alpha = 0.6f),
        requiredMarker = Rust,
        pickerBackdrop = Espresso,
        pickerDial = Umber,
        pickerDialContent = Wheat,
        pickerSelector = Rust,
        pickerSelectorContent = Cream,
        pickerChipSelectedContainer = Rust,
        pickerChipSelectedContent = Cream,
        buttonContainer = Rust,
        buttonContent = Cream,
        buttonDisabledContainer = Rust.copy(alpha = 0.5f),
        buttonDisabledContent = Cream.copy(alpha = 0.5f),
        chipSelectedContainer = Rust,
        chipSelectedContent = Cream,
        chipContainer = Rust.copy(alpha = 0.12f),
        chipContent = Wheat,
        fabContainer = Ochre,
        fabContent = Espresso,
        actionIcon = Ochre,
        bottomNavContainer = Espresso,
        bottomNavIndicator = Ochre,
        bottomNavActiveIcon = Espresso,
        bottomNavInactiveIcon = Wheat,
        calendarCellContainer = Espresso,
        calendarWeekendContainer = Umber,
        calendarTodayContainer = Rust,
        calendarDayNumber = Wheat,
        calendarTodayNumber = Cream,
        calendarAdjacentDayNumber = Wheat.copy(alpha = 0.4f),
        calendarHeader = Wheat,
        calendarWeekdayLabel = Rust,
        calendarEventMarker = Ochre,
        calendarNoteMarker = Rust,
        calendarPastMarker = Fog,
        sectionTitle = Ochre,
        brandLogo = Ochre,
        brandTitle = Ochre,
        launchBackground = Ink,
        appBarScrolledContainer = Umber,
    ),
)

internal fun themeSpecOf(kind: ThemeKind): AppThemeSpec = when (kind) {
    ThemeKind.DARK -> DarkTheme
    ThemeKind.LIGHT -> LightTheme
    ThemeKind.OCEAN -> OceanTheme
    ThemeKind.FOREST -> ForestTheme
    ThemeKind.AUTUMN -> AutumnTheme
}
